name: Push To Master

on: 
  push:
    branches:
    - master

jobs:
  prepare:
    name: Project Preparation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1

      - run: yarn install
      - run: yarn lerna bootstrap
      - run: yarn lint

