name: Push To Master

on: 
  push:
    branches:
    - master

jobs:
  prepare:
    name: Project Preparation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1

      - run: yarn install
      - run: yarn lerna bootstrap
      - run: yarn lerna run build --stream --ignore @chrispcode/knack-storybook
      - run: yarn lint
      - run: yarn lerna run build --stream --scope @chrispcode/knack-storybook
      - run: yarn version:storybook
      - run: echo $(cat _STORYBOOK_VERSION)
      - run: docker build -f docker/storybook.Dockerfile -t docker.pkg.github.com/chrispcode/knack/storybook:$(cat _STORYBOOK_VERSION) -t docker.pkg.github.com/chrispcode/knack/storybook .

