name: Push To Master

on: 
  push:
    branches:
    - master

jobs:
  prepare:
    name: Project Preparation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
  
    - name: Install
      uses: actions/setup-node@v1
      run: yarn install
    - name: Bootstrap
      run: lerna bootstrap
